---
#########################################################################################
##
## This playbook deploys the portal dev docker environment locally
##
#########################################################################################
- name: ansible-cloudconfig installer
  hosts: core
  vars:
    author: johnt337
    project: cloudconfig
    cloudconfig_dest: /home/core/bin/cloudconfig
    ansible_mod_dest: /usr/local/etc/ansible/library/cloudconfig_user.py
    #########################################################################################
    ##
    ## Tasks to install the cloudconfig binary and this role's modules
    ##
    #########################################################################################

  tasks:
    #########################################################################################
    ##
    ## Installer Section
    ##
    #########################################################################################
    - name: get latest build number
      shell: "curl -s -X GET 'https://circleci.com/api/v1/project/{{ author }}/{{ project }}' | grep build_num | head -1 | awk -F{{':'}} '{print$2}' | sed -e 's/[ ,]//g'"
      register: build_num

    - debug: msg="latest build number - {{ item }}"
      with_items: build_num.stdout_lines

    - name: get download url
      shell: "curl -s -X GET 'https://circleci.com/api/v1/project/{{ author }}/{{ project }}/{{ item }}/artifacts' | grep bin | head -1 | grep url | awk -F{{':'}} '{print$2$3}'ß"
      register: download
      with_items: build_num.stdout_lines

    - debug: msg="fetching - {{ item }}"
      with_items: download.stdout_lines

    - name: download cloudconfig binary
      shell: "curl -s -L -X GET '{{ item }}' > '{{cloudconfig_dest}}'"
      with_items: download.stdout_lines

    - name: install cloudconfig_user module
      local_action: copy src="library/cloudconfig_user.py" dest="{{ ansible_mod_dest }}" owner="core" mode=0750

    - name: install cloudconfig_user module
      local_action: copy src="library/cloudconfig_user.py" dest="{{ ansible_mod_dest }}" owner="core" mode=0750
    #########################################################################################
    ##
    ## Uninstaller Section
    ##
    #########################################################################################
    - name: uninstall build files
      file: path="{{cloudconfig_dest}}" state=absent
      with_items: files
      when: uninstall is defined
