---
#########################################################################################
##
## This playbook deploys the portal dev docker environment locally
##
#########################################################################################
- name: ansible-cloudconfig installer
  hosts: core
  vars:
    author: johnt337
    project: cloudconfig
    cloudconfig_dest: /home/core/bin/cloudconfig
    ansible_mod_folder: /usr/local/etc/ansible/library/
    ansible_mod_dest: "{{ansible_mod_folder}}/cloudconfig_user.py"
    #########################################################################################
    ##
    ## Tasks to install the cloudconfig binary and this role's modules
    ##
    #########################################################################################

  tasks:
    #########################################################################################
    ##
    ## Installer Section
    ##
    #########################################################################################
    - name: copy cloudconfig url generator
      copy: src=files/get_build_url.sh dest=/tmp/get_build_url.sh owner="core" group="wheel" mode=0550

    - name: get download url
      command: /tmp/get_build_url.sh {{author}} {{project}}
      register: download

    - name: download cloudconfig binary
      get_url: url='{{ item }}' dest='{{cloudconfig_dest}}' mode=0550 owner=core group=wheel
      with_items: download.stdout

    - name: cloudconfig_user install folder
      local_action: file path="{{ ansible_mod_folder }}" mode=0750 state=directory
      when: local is defined
    
    - name: install cloudconfig_user module
      local_action: copy src="files/library/cloudconfig_user.py" dest="{{ ansible_mod_dest }}" mode=0550
      when: local is defined

    #########################################################################################
    ##
    ## Uninstaller Section
    ##
    #########################################################################################
    - name: uninstall cloudconfig binary on remote hosts
      file: path="{{cloudconfig_dest}}" state=absent
      when: uninstall is defined

    - name: uninstall ansible module locally
      local_action: file path="{{ansible_mod_folder}}" state=absent
      when: uninstall is defined and local is defined

    - name: uninstall get_build_url.sh
      file: path="/tmp/get_build_url.sh" state=absent
      when: uninstall is defined
