---
#########################################################################################
##
## This playbook deploys the portal dev docker environment locally
##
#########################################################################################
- name: ansible-cloudconfig installer
  hosts: core
  vars:
    author: johnt337
    project: cloudconfig
    cloudconfig_dest: /home/core/bin/cloudconfig
    ansible_mod_folder: /usr/local/etc/ansible/library/
    ansible_mod_dest: "{{ansible_mod_folder}}/cloudconfig_user.py"
    #########################################################################################
    ##
    ## Tasks to install the cloudconfig binary and this role's modules
    ##
    #########################################################################################

  tasks:
    #########################################################################################
    ##
    ## Installer Section
    ##
    #########################################################################################
    - name: copy cloudconfig url generator
      copy: src=files/get_build_url.sh dest=/tmp/get_build_url.sh owner="core" group="wheel" mode=0550

    - name: get download url
      command: /tmp/get_build_url.sh {{author}} {{project}}
      register: download

    - debug: msg="downloading - {{ item }}"
      with_items: download.stdout

    - name: download cloudconfig binary
      # shell: "curl -s -L -X GET '{{ item }}' -o '{{cloudconfig_dest}}'"
      get_url: url='{{ item }}' dest='{{cloudconfig_dest}}' mode=0550 owner=core group=wheel
      # args:
         # creates: "{{cloudconfig_dest}}"
      with_items: download.stdout

    - name: set permissions and ownership on cloudconfig
      file: path="{{cloudconfig_dest}}" owner="core" group="wheel" mode=0550

    - name: cloudconfig_user install folder
      local_action: file path="{{ ansible_mod_folder }}" mode=0750 state=directory
    
    - name: install cloudconfig_user module
      local_action: copy src="files/library/cloudconfig_user.py" dest="{{ ansible_mod_dest }}" mode=0550

    #########################################################################################
    ##
    ## Uninstaller Section
    ##
    #########################################################################################
    - name: uninstall build files
      file: path="{{cloudconfig_dest}}" state=absent
      with_items: files
      when: uninstall is defined
